com.github.tchx84.Flatseal
com.ranfdev.DistroShelf
io.github.flattool.Warehouse
io.github.kolunmi.Bazaar
io.missioncenter.MissionCenter
org.deskflow.deskflow
org.fedoraproject.MediaWriter
org.fkoehler.KTailctl
org.gnome.DejaDup
org.gtk.Gtk3theme.Breeze
org.kde.gwenview
org.kde.haruna
org.kde.kcalc
org.kde.kclock
org.kde.kontact
org.kde.kweather
org.kde.okular
org.kde.skanpage
org.mozilla.Thunderbird
org.mozilla.firefox
