name: Latest Images
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
      - "iso_files/**"
      - "flatpaks/**"
      - ".github/workflows/*iso*"
      - "system_files/shared/usr/share/ublue-os/bazaar/config.yaml"
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-latest:
    name: Build Latest Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["aurora"]
    with:
      image_flavors: '["main", "nvidia", "nvidia-open"]'
      brand_name: ${{ matrix.brand_name }}
      stream_name: latest
      #kernel_pin: 6.12.15-200.fc41.x86_64

  generate-release:
    name: Generate Release
    needs: [build-image-latest]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["latest"]'
