# We have this because we can't schedule builds on non-default branches
name: Trigger Stable Image Build
on:
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1:15 AM
  workflow_dispatch:

permissions: {}

jobs:
  trigger-stable-build:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Trigger Stable Image Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ vars.STABLE_BRANCH }}
        run: |
          gh workflow run \
            build-image-stable.yml \
            --ref "${BRANCH}"
