# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[line_break]
disabled = true

[username]
style_user = 'blue bold'
style_root = 'red bold'
format = ' [$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold gray) at [$hostname](bold blue) '
disabled = false

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '


